In [1]:
# Imports
import numpy as np

In [12]:
# Making 1-D arrays
arry1 = np.array([1, 2, 3])
print('arry1 is: ',arry1)
print('type: ',type(arry1))
arry1

arry1 is:  [1 2 3]
type:  <class 'numpy.ndarray'>


array([1, 2, 3])

In [15]:
# Making 2-D arrays and specifying datatypes
list_in = [[1, 2, 3], [4, 5, 6]]
arry2 = np.array(list_in, dtype='float')
print(arry2)
arry2

[[1. 2. 3.]
 [4. 5. 6.]]


array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
# Converting types:
arry3 = arry2.astype('int')
arry3
# Note: You an also make arrays of type 'object' and have strings and stuff in them!

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# Converting back to lists:
list3 = arry3.tolist()
list3

[[1, 2, 3], [4, 5, 6]]

In [28]:
# Referencing parts of arrays
arry3[1][:2] # ':' can be read as 'up to but not including' in a zero-indexed system.
             # otherwise it's very similar to regular lists


array([4, 5])

In [32]:
# Getting info on arrays:
print('Number of dimensions in arry3:',arry3.ndim)
print('Shape of arry3:',arry3.shape) # linear algebra ordering. Returns tuple.
print('Datatype of arry3:',arry3.dtype)


Number of dimensions in arry3: 2
Shape of arry3: (2, 3)
Datatype of arry3: int64


In [38]:
# Boolean indexing:
arry_bool = arry3 > 3
print('Parts of arry3 > 3:\n',arry_bool)
print('arry3 at those points: ', arry3[arry_bool])

Parts of arry3 > 3:
 [[False False False]
 [ True  True  True]]
arry3 at those points:  [4 5 6]


In [54]:
# nan and inf: remember that nan and inf are floats...
arry3 = arry3.astype('float')
arry3[0,0] = np.nan
arry3[0,1] = np.inf
arry3

array([[nan, inf,  3.],
       [ 4.,  5.,  6.]])

In [55]:

missing_parts = np.isnan(arry3) | np.isinf(arry3)
arry3[missing_parts] = -1
arry3

array([[-1., -1.,  3.],
       [ 4.,  5.,  6.]])

In [118]:
print(arry3.max())
print(arry3.min())

print('Min per column: ',np.amin(arry3, axis=0))
print('Min per row: ', np.amin(arry3, axis=1))

6.0
-1.0
Min per column:  [-1. -1.  3.]
Min per row:  [-1.  4.]


In [119]:
# Creating new array from existing array
arry3_cpy = arry3.copy()
arry3_notcpy = arry3

In [120]:
# Flattening
flat = arry3.flatten()
flat

array([-1., -1.,  3.,  4.,  5.,  6.])

In [121]:
# np.arange(...) works the same as range() and generates that as an np array.
inArry = np.arange(0, 36)
outArry = inArry.reshape(6, 6)
outArry

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [122]:
append = np.array([4, 1, 4, 2, 3, 4])
append = append.reshape((1, 6))
outArry = np.concatenate((outArry, append), axis=0)
outArry

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [ 4,  1,  4,  2,  3,  4]])

In [123]:
append = np.arange(7)
append = append.reshape((1, append.shape[0]))
append = np.transpose(append)
outArry = np.concatenate((outArry, append), axis = 1)
outArry

array([[ 0,  1,  2,  3,  4,  5,  0],
       [ 6,  7,  8,  9, 10, 11,  1],
       [12, 13, 14, 15, 16, 17,  2],
       [18, 19, 20, 21, 22, 23,  3],
       [24, 25, 26, 27, 28, 29,  4],
       [30, 31, 32, 33, 34, 35,  5],
       [ 4,  1,  4,  2,  3,  4,  6]])

In [126]:
labels = outArry[:, outArry.shape[1]-1]
labels

array([0, 1, 2, 3, 4, 5, 6])

In [127]:
outArry = outArry[:, :(outArry.shape[1]-1)]
outArry

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [ 4,  1,  4,  2,  3,  4]])

In [128]:
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [129]:
# Model initialization
regression_model = LinearRegression()
# Fit the data(train the model)
regression_model.fit(outArry, labels)
# Predict
y_predicted = regression_model.predict(outArry)


In [130]:
y_predicted

array([7.99360578e-15, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00,
       4.00000000e+00, 5.00000000e+00, 6.00000000e+00])

In [131]:
regression_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)